---
mackerel__config_folder: "{{ playbook_dir }}/mackerel"
mackerel__remote_config_folder: "/mackerel/projects/{{ project_name }}"
mackerel__remote_config_file: "{{ mackerel__remote_config_folder }}/project.yml"
mackerel__local_config_file: "{{ mackerel__config_folder }}/{{ project_name }}.yml"
