---
mackerel__config_folder: "{{ playbook_dir }}/mackerel"
mackerel__remote_config_folder: "/mackerel/config/applications"
mackerel__local_config_file: "{{ mackerel__config_folder }}/{{ project_name }}.yaml"
mackerel__remote_config_file: "{{ mackerel__remote_config_folder }}/{{ project_name }}.yml"