---
- name: "Check if tfstate exists"
  stat:
    path: "{{ item }}/terraform.tfstate"
  register: tfstate_exist
- name: "Replace Terraform provider {{ provider_old }} -> {{ provider_new }}"
  shell:
    cmd: "terraform state replace-provider '{{ provider_old }}' '{{ provider_new }}'"
    chdir: "{{ item }}"
  when: tfstate_exist.stat.exists
