---
- import_tasks: "roles/mackerel_setup/tasks/facts-load.yml"
  ignore_errors: yes

- name: Validate server configuration file
  assert:
    that:
      - mackerel.capabilities.php is not defined or (mackerel.capabilities.php is defined and mackerel.capabilities.php is defined)

- import_tasks: "roles/mackerel_setup/tasks/facts-deploy.yml"

- import_tasks: "roles/mackerel_setup/tasks/setup-nginx.yml"

- import_tasks: "roles/mackerel_setup/tasks/setup-docker.yml"

- import_tasks: "roles/mackerel_setup/tasks/setup-php.yml"
  when: mackerel.capabilities.php is defined

- name: "Write Mackerel version"
  debug:
    msg: "test"