name: 'StackHead CLI'
description: 'Deploy a project definition file to your server that was prepared for StackHead.'
author: 'Mario Lubenka'
inputs:
  ipaddress:
    description: 'IP address of the server'
    required: true
  file:
    description: 'Project definition file'
    required: true
  version:
    description: 'Version of StackHead to use (default: master)'
    required: false
    default: master
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.ipaddress }}
    - ${{ inputs.file }}
