---
- name: Update apt caches
  apt:
    update_cache: yes
- import_role:
    name: andrewrothstein.python
- import_role:
    name: nickjj.docker
- name: Make sure docker pip package is up to date
  pip:
    name: docker
    extra_args: --upgrade
- name: Install Wheel (required for docker-compose)
  pip:
    name: wheel
- name: Install docker-compose
  pip:
    name: docker-compose