---
- name: Deploy additional h5bp Nginx files
  synchronize:
    src: "{{ playbook_dir }}/vendor/server-configs-nginx/h5bp"
    dest: /etc/nginx
- name: Setup Nginx
  vars:
    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf.j2"
    nginx_vhosts: []
  include_role:
    name: geerlingguy.nginx